# generated by datamodel-codegen:
#   filename:  tmp.3zznmIBIEX
#   timestamp: 2026-06-03T21:10:55+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Account(BaseModel):
    balance: str = Field(..., description='Cash balance (excluding unrealized P&L).')
    currency: str = Field(
        ..., description='Account base currency (e.g., "USD", "EUR").'
    )
    equity: str = Field(..., description='Total equity (balance + unrealized P&L).')
    margin_available: str = Field(
        ..., description='Available margin for new positions.'
    )
    margin_used: str = Field(
        ..., description='Margin currently in use for open positions.'
    )
    unrealized_pnl: str = Field(
        ..., description='Total unrealized P&L across all open positions.'
    )


class AccountEventType(StrEnum):
    BALANCE_UPDATED = 'BALANCE_UPDATED'
    MARGIN_WARNING = 'MARGIN_WARNING'
    MARGIN_CALL = 'MARGIN_CALL'


class AssetClass(StrEnum):
    STOCK = 'STOCK'
    FOREX = 'FOREX'
    CRYPTO = 'CRYPTO'
    FUTURES = 'FUTURES'


class CancelAllOrdersParams(BaseModel):
    symbol: str | None = Field(
        None, description='Filter by symbol (None = cancel all orders)'
    )


class CancelAllResult(BaseModel):
    cancelled_count: int = Field(
        ..., description='Number of orders successfully cancelled', ge=0
    )
    failed_count: int = Field(
        ..., description='Number of orders that failed to cancel', ge=0
    )
    failed_order_ids: list[str] | None = Field(
        None, description='IDs of orders that failed to cancel'
    )


class CircuitBreakerSnapshot(BaseModel):
    failure_count: int = Field(
        ..., description='Number of recent failures within the time window.', ge=0
    )
    state: str = Field(..., description='Current state: `"open"` or `"closed"`.')


class CircuitBreakerStatusResponse(BaseModel):
    adapter: CircuitBreakerSnapshot = Field(
        ..., description='Adapter circuit breaker (provider outage detection).'
    )
    exit_order: CircuitBreakerSnapshot = Field(
        ...,
        description='Exit order circuit breaker (SL/TP placement failure detection).',
    )


class CloseAllPositionsParams(BaseModel):
    symbol: str | None = Field(
        None, description='Filter by symbol (None = close all positions)'
    )


class ConnectionEventType(StrEnum):
    CONNECTED = 'CONNECTED'
    DISCONNECTING = 'DISCONNECTING'
    RECONNECTING = 'RECONNECTING'
    BROKER_DISCONNECTED = 'BROKER_DISCONNECTED'
    BROKER_RECONNECTED = 'BROKER_RECONNECTED'
    BROKER_CONNECTION_FAILED = 'BROKER_CONNECTION_FAILED'


class ConnectionStatus(BaseModel):
    connected: bool = Field(
        ..., description='Whether the connection to the provider is active'
    )
    last_heartbeat: AwareDatetime = Field(
        ..., description='Timestamp of last successful heartbeat/ping'
    )
    latency_ms: int = Field(..., description='Round-trip latency in milliseconds', ge=0)


class DataStalenessEventType(StrEnum):
    STALE = 'STALE'
    FRESH = 'FRESH'


class ErrorCode(StrEnum):
    INVALID_REQUEST = 'INVALID_REQUEST'
    INVALID_VALUE = 'INVALID_VALUE'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    UNAUTHORIZED = 'UNAUTHORIZED'
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND'
    POSITION_NOT_FOUND = 'POSITION_NOT_FOUND'
    SYMBOL_NOT_FOUND = 'SYMBOL_NOT_FOUND'
    OCO_GROUP_NOT_FOUND = 'OCO_GROUP_NOT_FOUND'
    ORDER_NOT_MODIFIABLE = 'ORDER_NOT_MODIFIABLE'
    RESET_COOLDOWN = 'RESET_COOLDOWN'
    ORDER_REJECTED = 'ORDER_REJECTED'
    RATE_LIMITED = 'RATE_LIMITED'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION'
    PROVIDER_ERROR = 'PROVIDER_ERROR'
    SHUTTING_DOWN = 'SHUTTING_DOWN'
    PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE'


class GetPositionsParams(BaseModel):
    symbol: str | None = Field(None, description='Optional symbol to filter positions.')


class HealthStatus(BaseModel):
    status: str = Field(..., description='Health status (always "ok" if responding)')


class MarginMode(StrEnum):
    CROSS = 'CROSS'
    ISOLATED = 'ISOLATED'


class ModifyOrderRequest(BaseModel):
    limit_price: str | None = Field(None, description='New limit price')
    quantity: str | None = Field(
        None, description='New total quantity (must be >= `filled_quantity`)'
    )
    stop_loss: str | None = Field(None, description='New stop loss price')
    stop_price: str | None = Field(None, description='New stop price')
    take_profit: str | None = Field(None, description='New take profit price')
    trailing_distance: str | None = Field(None, description='New trailing distance')


class OrderEventType(StrEnum):
    ORDER_CREATED = 'ORDER_CREATED'
    ORDER_MODIFIED = 'ORDER_MODIFIED'
    ORDER_CANCELLED = 'ORDER_CANCELLED'
    ORDER_REJECTED = 'ORDER_REJECTED'
    ORDER_FILLED = 'ORDER_FILLED'
    ORDER_PARTIALLY_FILLED = 'ORDER_PARTIALLY_FILLED'
    ORDER_EXPIRED = 'ORDER_EXPIRED'
    BRACKET_ORDER_CREATED = 'BRACKET_ORDER_CREATED'
    BRACKET_ORDER_MODIFIED = 'BRACKET_ORDER_MODIFIED'


class OrderStatus(StrEnum):
    PENDING = 'PENDING'
    PENDING_CANCEL = 'PENDING_CANCEL'
    OPEN = 'OPEN'
    PARTIALLY_FILLED = 'PARTIALLY_FILLED'
    FILLED = 'FILLED'
    CANCELLED = 'CANCELLED'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'


class OrderType(StrEnum):
    MARKET = 'MARKET'
    LIMIT = 'LIMIT'
    STOP = 'STOP'
    STOP_LIMIT = 'STOP_LIMIT'
    TRAILING_STOP = 'TRAILING_STOP'


class OverallStatus(StrEnum):
    CONNECTED = 'connected'
    DEGRADED = 'degraded'


class PingPayload(BaseModel):
    timestamp: AwareDatetime = Field(..., description='Server timestamp.')


class PositionEventType(StrEnum):
    POSITION_OPENED = 'POSITION_OPENED'
    POSITION_MODIFIED = 'POSITION_MODIFIED'
    POSITION_CLOSED = 'POSITION_CLOSED'


class PositionMode(StrEnum):
    NETTING = 'NETTING'
    HEDGING = 'HEDGING'


class PositionSide(StrEnum):
    LONG = 'LONG'
    SHORT = 'SHORT'


class ProviderHealth(BaseModel):
    connected: bool = Field(..., description='Whether all instrument data is fresh')
    platform: str = Field(..., description='Platform identifier')
    stale_instruments: list[str] | None = Field(
        None, description='Instruments with stale data (empty when healthy)'
    )


class Quote(BaseModel):
    ask: str = Field(..., description='Best ask price (lowest sell offer)')
    ask_size: str | None = Field(None, description='Quantity available at ask price')
    bid: str = Field(..., description='Best bid price (highest buy offer)')
    bid_size: str | None = Field(None, description='Quantity available at bid price')
    last: str = Field(..., description='Last traded price')
    provider: str = Field(
        ..., description='Data source provider (e.g., "alpaca", "binance")'
    )
    symbol: str = Field(
        ...,
        description='Symbol in the provider\'s native format, exactly as subscribed (e.g., "F:EURUSD", "AAPL").\nThe gateway does not normalise symbols; use the same form your strategy subscribed with.',
    )
    timestamp: AwareDatetime = Field(..., description='Quote timestamp')
    volume: str | None = Field(None, description='Trading volume (if available)')


class RateLimitEventType(StrEnum):
    RATE_LIMIT_WARNING = 'RATE_LIMIT_WARNING'
    RATE_LIMIT_HIT = 'RATE_LIMIT_HIT'


class RateLimits(BaseModel):
    orders_per_day: int | None = Field(None, description='Maximum orders per day', ge=0)
    orders_per_second: int | None = Field(
        None, description='Maximum order submissions per second', ge=0
    )
    requests_per_minute: int | None = Field(
        None, description='Maximum API requests per minute', ge=0
    )


class ReadyStatus(BaseModel):
    message: str | None = Field(
        None, description='Optional message explaining non-ready state'
    )
    provider_count: int = Field(..., description='Number of registered providers', ge=0)
    providers: list[str] = Field(..., description='List of registered provider names')
    ready: bool = Field(
        ..., description='Whether the service is ready to accept requests'
    )


class RejectReason(StrEnum):
    INSUFFICIENT_MARGIN = 'INSUFFICIENT_MARGIN'
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
    INVALID_QUANTITY = 'INVALID_QUANTITY'
    INVALID_PRICE = 'INVALID_PRICE'
    SYMBOL_NOT_TRADEABLE = 'SYMBOL_NOT_TRADEABLE'
    MARKET_CLOSED = 'MARKET_CLOSED'
    REDUCE_ONLY_VIOLATED = 'REDUCE_ONLY_VIOLATED'
    POST_ONLY_VIOLATED = 'POST_ONLY_VIOLATED'
    RATE_LIMITED = 'RATE_LIMITED'
    UNKNOWN = 'UNKNOWN'


class Side(StrEnum):
    BUY = 'BUY'
    SELL = 'SELL'


class TimeInForce(StrEnum):
    GTC = 'GTC'
    DAY = 'DAY'
    IOC = 'IOC'
    FOK = 'FOK'


class Timeframe(StrEnum):
    FIELD_1M = '1m'
    FIELD_2M = '2m'
    FIELD_5M = '5m'
    FIELD_10M = '10m'
    FIELD_15M = '15m'
    FIELD_30M = '30m'
    FIELD_1H = '1h'
    FIELD_2H = '2h'
    FIELD_4H = '4h'
    FIELD_12H = '12h'
    FIELD_1D = '1d'
    FIELD_1W = '1w'


class Trade(BaseModel):
    commission: str = Field(..., description='Commission/fee amount for this trade')
    commission_currency: str = Field(
        ..., description='Currency of the commission (e.g., "USD", "USDT", "BNB")'
    )
    id: str = Field(..., description='Unique trade identifier from provider')
    is_maker: bool | None = Field(
        None, description='Whether this trade was a maker (added liquidity) or taker.'
    )
    order_id: str = Field(..., description='Order ID this trade belongs to')
    price: str = Field(..., description='Fill price')
    quantity: str = Field(..., description='Fill quantity in base units')
    side: Side = Field(..., description='Trade side (buy or sell)')
    symbol: str = Field(..., description='Symbol traded')
    timestamp: AwareDatetime = Field(..., description='Trade execution timestamp')


class TradeEventType(StrEnum):
    TRADE_FILLED = 'TRADE_FILLED'


class TradeQueryParams(BaseModel):
    limit: int | None = Field(
        None, description='Maximum number of trades to return', ge=0
    )
    order_id: str | None = Field(None, description='Filter by order ID')
    since: AwareDatetime | None = Field(
        None, description='Return trades after this time (inclusive)'
    )
    symbol: str | None = Field(None, description='Filter by symbol')
    until: AwareDatetime | None = Field(
        None, description='Return trades before this time (exclusive)'
    )


class TradingPlatform(StrEnum):
    ALPACA_LIVE = 'alpaca-live'
    ALPACA_PAPER = 'alpaca-paper'
    BINANCE_SPOT_LIVE = 'binance-spot-live'
    BINANCE_SPOT_TESTNET = 'binance-spot-testnet'
    BINANCE_FUTURES_LIVE = 'binance-futures-live'
    BINANCE_FUTURES_TESTNET = 'binance-futures-testnet'
    BINANCE_MARGIN_LIVE = 'binance-margin-live'
    BINANCE_MARGIN_TESTNET = 'binance-margin-testnet'
    BINANCE_COIN_FUTURES_LIVE = 'binance-coin-futures-live'
    BINANCE_COIN_FUTURES_TESTNET = 'binance-coin-futures-testnet'
    OANDA_PRACTICE = 'oanda-practice'
    OANDA_LIVE = 'oanda-live'
    SAXO_SIM = 'saxo-sim'
    SAXO_LIVE = 'saxo-live'
    TEKTII = 'tektii'
    MOCK = 'mock'


class TrailingType(StrEnum):
    ABSOLUTE = 'ABSOLUTE'
    PERCENT = 'PERCENT'


class WsErrorCode(StrEnum):
    INVALID_MESSAGE = 'INVALID_MESSAGE'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    POSITION_UNPROTECTED = 'POSITION_UNPROTECTED'
    LIQUIDATION = 'LIQUIDATION'
    OCO_DOUBLE_EXIT = 'OCO_DOUBLE_EXIT'


class Type(StrEnum):
    PONG = 'pong'


class WsMessage1(BaseModel):
    type: Type


class Type1(StrEnum):
    EVENT_ACK = 'event_ack'


class WsMessage2(BaseModel):
    correlation_id: str = Field(
        ..., description='Unique correlation ID for tracking this acknowledgment.'
    )
    events_processed: list[str] = Field(
        ..., description='List of event IDs that were processed by the strategy.'
    )
    timestamp: int = Field(
        ...,
        description='Unix timestamp (milliseconds) when events were processed.',
        ge=0,
    )
    type: Type1


class Type2(StrEnum):
    PING = 'ping'


class WsMessage3(BaseModel):
    timestamp: AwareDatetime = Field(..., description='Server timestamp.')
    type: Type2


class Type3(StrEnum):
    ORDER = 'order'


class Type4(StrEnum):
    POSITION = 'position'


class Type5(StrEnum):
    ACCOUNT = 'account'


class WsMessage6(BaseModel):
    account: Account = Field(..., description='Current account state.')
    event: AccountEventType = Field(..., description='Type of account event.')
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type5


class Type6(StrEnum):
    CANDLE = 'candle'


class Type7(StrEnum):
    QUOTE = 'quote'


class WsMessage8(BaseModel):
    quote: Quote = Field(
        ..., description='The quote data (includes symbol, provider, bid/ask/last).'
    )
    timestamp: AwareDatetime = Field(
        ..., description='Event timestamp (when event was emitted).'
    )
    type: Type7


class Type8(StrEnum):
    TRADE = 'trade'


class WsMessage9(BaseModel):
    event: TradeEventType = Field(..., description='Type of trade event.')
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    trade: Trade = Field(..., description='The executed trade.')
    type: Type8


class Type9(StrEnum):
    CONNECTION = 'connection'


class WsMessage10(BaseModel):
    broker: str | None = Field(
        None,
        description='Broker/platform name (e.g., "alpaca-paper"). Present for broker events.',
    )
    error: str | None = Field(
        None, description='Error message if disconnecting/reconnecting due to error.'
    )
    event: ConnectionEventType = Field(..., description='Type of connection event.')
    gap_duration_ms: int | None = Field(
        None,
        description='Duration of the connection gap in milliseconds (for `BrokerReconnected`).',
        ge=0,
    )
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type9


class Type10(StrEnum):
    DATA_STALENESS = 'data_staleness'


class WsMessage11(BaseModel):
    broker: str | None = Field(None, description='Broker/platform name.')
    event: DataStalenessEventType = Field(
        ..., description='Whether data became stale or fresh.'
    )
    stale_since: AwareDatetime | None = Field(
        None,
        description='When the data became stale. Present on both Stale (the moment it\nhappened) and Fresh (for gap duration calculation) events.',
    )
    symbols: list[str] = Field(..., description='Affected instrument symbols.')
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type10


class Type11(StrEnum):
    RATE_LIMIT = 'rate_limit'


class WsMessage12(BaseModel):
    event: RateLimitEventType = Field(..., description='Type of rate limit event.')
    requests_remaining: int = Field(
        ..., description='Number of requests remaining in current window.', ge=0
    )
    reset_at: AwareDatetime = Field(
        ..., description='When the rate limit window resets.'
    )
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type11


class Type12(StrEnum):
    ERROR = 'error'


class WsMessage13(BaseModel):
    code: WsErrorCode = Field(..., description='Error code.')
    details: Any | None = Field(None, description='Additional error details.')
    message: str = Field(..., description='Human-readable error message.')
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type12


class Type13(StrEnum):
    BACKTEST_COMPLETE = 'backtest_complete'


class WsMessage14(BaseModel):
    broker: str | None = Field(
        None, description='Broker/platform name (e.g. "tektii").'
    )
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type13


class ApiError(BaseModel):
    code: ErrorCode = Field(
        ...,
        description='Machine-readable error code (e.g., `ORDER_NOT_FOUND`, `RATE_LIMITED`)',
    )
    details: Any | None = Field(
        None, description='Additional error context (varies by error type)'
    )
    message: str = Field(..., description='Human-readable error message')


class Bar(BaseModel):
    close: str = Field(..., description='Closing price')
    high: str = Field(..., description='Highest price during the period')
    low: str = Field(..., description='Lowest price during the period')
    open: str = Field(..., description='Opening price')
    provider: str = Field(..., description='Data source provider')
    symbol: str = Field(
        ...,
        description='Symbol in the provider\'s native format, exactly as subscribed (e.g., "F:EURUSD", "AAPL").\nThe gateway does not normalise symbols; use the same form your strategy subscribed with.',
    )
    timeframe: Timeframe = Field(..., description='Bar timeframe')
    timestamp: AwareDatetime = Field(..., description='Bar start timestamp')
    volume: str = Field(..., description='Trading volume during the period')


class BarParams(BaseModel):
    end: AwareDatetime | None = Field(None, description='End of date range (inclusive)')
    limit: int | None = Field(
        None, description='Maximum number of bars to return', ge=0
    )
    start: AwareDatetime | None = Field(
        None, description='Start of date range (inclusive)'
    )
    timeframe: Timeframe = Field(..., description='Bar timeframe/interval')


class Capabilities(BaseModel):
    features: list[str] = Field(..., description='List of supported optional features.')
    max_leverage: str | None = Field(
        None, description='Maximum leverage multiplier (if applicable)'
    )
    position_mode: PositionMode = Field(
        ..., description='Position mode (netting vs hedging)'
    )
    rate_limits: RateLimits | None = None
    supported_asset_classes: list[AssetClass] = Field(
        ..., description='Asset classes supported by this provider'
    )
    supported_order_types: list[OrderType] = Field(
        ..., description='Order types supported by this provider'
    )


class ClosePositionRequest(BaseModel):
    cancel_associated_orders: bool | None = Field(
        None,
        description='Cancel pending SL/TP orders for this position (default: true)',
    )
    limit_price: str | None = Field(
        None, description='Limit price (required if `order_type` is LIMIT)'
    )
    order_type: OrderType | None = None
    quantity: str | None = Field(
        None, description='Quantity to close (None = close entire position)'
    )


class DetailedHealthStatus(BaseModel):
    git_sha: str = Field(
        ...,
        description='Git SHA of the build, baked in via the `GIT_SHA` env var at image\nbuild time. `"unknown"` when the binary was built without it (e.g. a\nlocal `cargo run`). Consumers — notably the canary capture binary —\nrely on this for dataset provenance, so the field name and semantics\nare stable.',
    )
    providers: list[ProviderHealth] = Field(
        ..., description='Per-provider health details'
    )
    status: OverallStatus = Field(
        ..., description='Overall status: "connected" or "degraded"'
    )
    version: str = Field(
        ..., description='Gateway semantic version (`CARGO_PKG_VERSION`), e.g. `0.1.0`.'
    )


class Order(BaseModel):
    average_fill_price: str | None = Field(
        None, description='Weighted average fill price'
    )
    client_order_id: str | None = Field(
        None, description='Client-provided order ID (if any)'
    )
    correlation_id: str | None = Field(
        None,
        description='Gateway-assigned correlation ID for tracing this order through its lifecycle.',
    )
    created_at: AwareDatetime = Field(..., description='When the order was created')
    display_quantity: str | None = Field(
        None, description='Display quantity for iceberg orders'
    )
    filled_quantity: str = Field(..., description='Quantity filled so far')
    hidden: bool | None = Field(None, description='Whether this is a hidden order')
    id: str = Field(..., description='Server-assigned order ID')
    limit_price: str | None = Field(
        None, description='Limit price (for LIMIT and `STOP_LIMIT` orders)'
    )
    oco_group_id: str | None = Field(
        None, description='OCO group ID if this order is part of an OCO pair.'
    )
    order_type: OrderType = Field(..., description='Order type')
    position_id: str | None = Field(
        None, description='Associated position ID (for hedging accounts)'
    )
    post_only: bool | None = Field(
        None, description='Whether this is a post-only order'
    )
    quantity: str = Field(..., description='Original order quantity')
    reduce_only: bool | None = Field(
        None, description='Whether this is a reduce-only order'
    )
    reject_reason: RejectReason | None = None
    remaining_quantity: str = Field(..., description='Quantity remaining')
    side: Side = Field(..., description='Order side')
    status: OrderStatus = Field(..., description='Current order status')
    stop_loss: str | None = Field(
        None, description='Stop loss price (for bracket orders)'
    )
    stop_price: str | None = Field(
        None, description='Stop price (for STOP and `STOP_LIMIT` orders)'
    )
    symbol: str = Field(..., description='Trading symbol')
    take_profit: str | None = Field(
        None, description='Take profit price (for bracket orders)'
    )
    time_in_force: TimeInForce = Field(..., description='Time in force')
    trailing_distance: str | None = Field(
        None, description='Trailing distance (for trailing stop orders)'
    )
    trailing_type: TrailingType | None = None
    updated_at: AwareDatetime = Field(
        ..., description='When the order was last updated'
    )


class OrderHandle(BaseModel):
    client_order_id: str | None = Field(
        None, description='Client-provided order ID (if any)'
    )
    correlation_id: str | None = Field(
        None,
        description='Gateway-assigned correlation ID for tracing this order through its lifecycle.',
    )
    id: str = Field(..., description='Server-assigned order ID')
    status: OrderStatus = Field(..., description='Initial order status')


class OrderQueryParams(BaseModel):
    client_order_id: str | None = Field(None, description='Filter by client order ID')
    limit: int | None = Field(
        None, description='Maximum number of orders to return', ge=0
    )
    oco_group_id: str | None = Field(None, description='Filter by OCO group ID')
    side: Side | None = None
    since: AwareDatetime | None = Field(
        None, description='Filter orders created after this time'
    )
    status: list[OrderStatus] | None = Field(
        None,
        description='Filter by status (multiple allowed, accepts comma-separated values)',
    )
    symbol: str | None = Field(None, description='Filter by symbol')
    until: AwareDatetime | None = Field(
        None, description='Filter orders created before this time'
    )


class OrderRequest(BaseModel):
    client_order_id: str | None = Field(
        None, description='Client-provided order ID for idempotency'
    )
    display_quantity: str | None = Field(
        None, description='Visible quantity for iceberg orders'
    )
    hidden: bool | None = Field(
        None, description='If true, order not visible in order book'
    )
    leverage: str | None = Field(None, description='Leverage multiplier')
    limit_price: str | None = Field(
        None, description='Required for LIMIT and `STOP_LIMIT` orders'
    )
    margin_mode: MarginMode | None = None
    oco_group_id: str | None = Field(
        None, description='OCO group ID to link orders (one-cancels-other).'
    )
    order_type: OrderType = Field(..., description='Order type')
    position_id: str | None = Field(
        None, description='Target position ID (for hedging accounts)'
    )
    post_only: bool | None = Field(
        None, description='If true, reject if would immediately fill (maker only)'
    )
    quantity: str = Field(..., description='Quantity in base units (must be positive)')
    reduce_only: bool | None = Field(
        None, description='If true, can only reduce position'
    )
    side: Side = Field(..., description='Buy or sell')
    stop_loss: str | None = Field(None, description='Stop loss price for bracket order')
    stop_price: str | None = Field(
        None, description='Required for STOP and `STOP_LIMIT` orders'
    )
    symbol: str = Field(
        ...,
        description='Symbol in the provider\'s native format, exactly as subscribed (e.g., "F:EURUSD", "AAPL").\nThe gateway does not normalise symbols; use the same form your strategy subscribed with.',
    )
    take_profit: str | None = Field(
        None, description='Take profit price for bracket order'
    )
    time_in_force: TimeInForce | None = Field(
        None, description='Time in force (default: GTC)'
    )
    trailing_distance: str | None = Field(
        None, description='Distance for `TRAILING_STOP` orders'
    )
    trailing_type: TrailingType | None = None


class Position(BaseModel):
    average_entry_price: str = Field(..., description='Weighted average entry price')
    current_price: str = Field(..., description='Current market price')
    id: str = Field(..., description='Position ID (may be synthetic for stock brokers)')
    leverage: str | None = Field(None, description='Leverage multiplier')
    liquidation_price: str | None = Field(
        None, description='Liquidation price (for leveraged positions)'
    )
    margin_mode: MarginMode | None = None
    opened_at: AwareDatetime = Field(..., description='When the position was opened')
    quantity: str = Field(..., description='Current position quantity')
    realized_pnl: str = Field(
        ..., description='Realized profit/loss (from partial closes)'
    )
    side: PositionSide = Field(..., description='Position direction (long or short)')
    symbol: str = Field(..., description='Trading symbol')
    unrealized_pnl: str = Field(..., description='Unrealized profit/loss')
    updated_at: AwareDatetime = Field(
        ..., description='When the position was last modified'
    )


class WsMessage4(BaseModel):
    event: OrderEventType = Field(..., description='Type of order event.')
    order: Order = Field(..., description='Current state of the order.')
    parent_order_id: str | None = Field(
        None, description='Parent order ID for bracket/OCO child orders.'
    )
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type3


class WsMessage5(BaseModel):
    event: PositionEventType = Field(..., description='Type of position event.')
    position: Position = Field(..., description='Current state of the position.')
    timestamp: AwareDatetime = Field(..., description='Event timestamp.')
    type: Type4


class WsMessage7(BaseModel):
    bar: Bar = Field(
        ..., description='The bar data (includes symbol, provider, timeframe, OHLCV).'
    )
    timestamp: AwareDatetime = Field(
        ..., description='Event timestamp (when event was emitted).'
    )
    type: Type6


class WsMessage(
    RootModel[
        WsMessage1
        | WsMessage2
        | WsMessage3
        | WsMessage4
        | WsMessage5
        | WsMessage6
        | WsMessage7
        | WsMessage8
        | WsMessage9
        | WsMessage10
        | WsMessage11
        | WsMessage12
        | WsMessage13
        | WsMessage14
    ]
):
    root: (
        WsMessage1
        | WsMessage2
        | WsMessage3
        | WsMessage4
        | WsMessage5
        | WsMessage6
        | WsMessage7
        | WsMessage8
        | WsMessage9
        | WsMessage10
        | WsMessage11
        | WsMessage12
        | WsMessage13
        | WsMessage14
    ) = Field(
        ...,
        description='All possible WebSocket messages.\n\nUses serde\'s internally tagged representation for clean JSON:\n```json\n{"type": "order", "event": "ORDER_FILLED", "order": {...}}\n{"type": "ping", "timestamp": "2025-01-01T00:00:00Z"}\n```\n\n# Client -> Server Messages\n\n- `Pong` - Response to server ping (heartbeat)\n- `EventAck` - Acknowledge processed events (required for simulation, optional for live)\n\n# Server -> Client Messages\n\n- `Ping` - Server heartbeat\n- `Order` - Order state change\n- `Position` - Position state change\n- `Account` - Account state change\n- `Connection` - Connection state change\n- `RateLimit` - Rate limit notification\n- `Error` - Error notification\n\n# Subscription Configuration\n\nNote: There are no Subscribe/Unsubscribe messages. Event subscriptions\nare configured at startup via environment variables (e.g., `SUBSCRIPTIONS`).',
    )


class CancelOrderResult(BaseModel):
    order: Order = Field(..., description='Updated order state')
    success: bool = Field(..., description='Whether cancellation succeeded')


class ModifyOrderResult(BaseModel):
    order: Order = Field(..., description='The modified (or replacement) order')
    previous_order_id: str | None = Field(
        None,
        description='Previous order ID if the provider used cancel-replace.\n`None` if the order was modified in-place.',
    )
