"""Tektii Gateway Python SDK."""

from tektii_gateway._version import __version__
from tektii_gateway.async_client import AsyncTektiiGateway
from tektii_gateway.client import TektiiGateway
from tektii_gateway.errors import (
    AuthenticationError,
    BadRequestError,
    ConflictError,
    NotFoundError,
    OrderRejectedError,
    ProviderUnavailableError,
    RateLimitedError,
    ServerError,
    TektiiAPIError,
    TektiiConnectionError,
    TektiiError,
    TektiiProtocolError,
)
from tektii_gateway.models import (
    Account,
    AccountEvent,
    AccountEventType,
    AssetClass,
    Bar,
    CancelAllResult,
    CandleEvent,
    Capabilities,
    ConnectionEvent,
    ConnectionEventType,
    ConnectionStatus,
    DataStalenessEvent,
    ErrorEvent,
    GatewayEvent,
    MarginMode,
    ModifyOrderResult,
    Order,
    OrderEvent,
    OrderEventType,
    OrderHandle,
    OrderStatus,
    OrderType,
    OverallStatus,
    Position,
    PositionEvent,
    PositionEventType,
    PositionMode,
    PositionSide,
    Quote,
    QuoteEvent,
    RateLimitEvent,
    RejectReason,
    Side,
    Timeframe,
    TimeInForce,
    Trade,
    TradeEvent,
    TradingPlatform,
    TrailingType,
    WsErrorCode,
)
from tektii_gateway.stream import AsyncEventStream, SyncEventStream

__all__ = [
    "__version__",
    # Clients
    "AsyncTektiiGateway",
    "TektiiGateway",
    # Streams
    "AsyncEventStream",
    "SyncEventStream",
    # Errors
    "TektiiError",
    "TektiiAPIError",
    "TektiiConnectionError",
    "TektiiProtocolError",
    "BadRequestError",
    "NotFoundError",
    "OrderRejectedError",
    "AuthenticationError",
    "RateLimitedError",
    "ConflictError",
    "ProviderUnavailableError",
    "ServerError",
    # Models
    "Account",
    "Bar",
    "CancelAllResult",
    "Capabilities",
    "ConnectionStatus",
    "ModifyOrderResult",
    "Order",
    "OrderHandle",
    "Position",
    "Quote",
    "Trade",
    # Enums
    "AssetClass",
    "MarginMode",
    "OrderStatus",
    "OrderType",
    "OverallStatus",
    "PositionMode",
    "PositionSide",
    "RejectReason",
    "Side",
    "Timeframe",
    "TimeInForce",
    "TradingPlatform",
    "TrailingType",
    "WsErrorCode",
    # Event types
    "AccountEventType",
    "ConnectionEventType",
    "OrderEventType",
    "PositionEventType",
    # WebSocket events
    "AccountEvent",
    "CandleEvent",
    "ConnectionEvent",
    "DataStalenessEvent",
    "ErrorEvent",
    "GatewayEvent",
    "OrderEvent",
    "PositionEvent",
    "QuoteEvent",
    "RateLimitEvent",
    "TradeEvent",
]
